### ISSUE TITLE
Refactor the Main Redcap Data Dictionary Parsing Loop, in Order to Support One-to-many Relationships Between Data Dictionary Fields and the Underlying Data Columns.

### ISSUE THREAD

**Issue by ShenZhouHong** [metrc/redcapschema#1]
Right now, the implementation of the REDCap data dictionary parser still naively assumes a one-to-one correspondence between every data dictionary entry, and every column of data in the actual data CSV. This was proven not to be the case in two examples:

1. **Descriptive fields**: these are purely informative. While they are defined in the data dictionary and show content on the REDCap UI, they do not actually have corresponding columns created in the data CSV.
2. **Multichoice fields**: a multichoice field like a checkbox actually results in the creation of *multiple* columns in the underlying data CSV, one for each checkbox option.

The first case (1.) can be handled relatively painlessly, but the second case where a data dictionary field may yield multiple, possibly dozens of data csv columns was not accounted for in the design of the main parsing loop.

Hence, the current code is unable to handle multichoice fields like checkboxes at all, and attempting to integrate support into it would not be feasible. This is because the main parsing loop creates a key-value pair in the schema for every data dictionary entry, and we cannot create multiple key-value pairs due to the way the loop is architectured:

```py
class Parser(ParseByFieldType):
    # ...
    def create_schema(self) -> dict:
        # ...
        # Iterate over indexes and rows in the data dictionary, storing them in columns
        for index, row in self.data_dict.iterrows():
            columns[index] = self.__parse_field_type(row)
    # ...
```

We will probably have to rewrite the parser and the main loop as a result.

**Comment by acarlini** [comment]
This is definitely something that needs to be worked around, however, it should hopefully be obvious at this point that the fields created from a checkbox are named in a standard manner [dictionary name + 3 underscores + stored value].  Not that I think this would be easily navigated, but I will note that an alternate presentation of the REDCap data dictionary exists that is more meant for an analyst using exported data.  But it does include the checkbox fields listed out in a manner that might be scraped if really desired:

https://www.metrcdata.org/redcap/redcap_v12.0.13/Design/data_dictionary_codebook.php?pid=157

Overall, I think you are likely to find a clever work around using knowledge of the naming convention…

From: Shen Zhou Hong ***@***.***>
Reply-To: metrc/redcapschema ***@***.***>
Date: Friday, August 19, 2022 at 11:56 AM
To: metrc/redcapschema ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [metrc/redcapschema] Refactor the Main Redcap Data Dictionary Parsing Loop, in Order to Support One-to-many Relationships Between Data Dictionary Fields and the Underlying Data Columns. (Issue #1)


Right now, the implementation of the REDCap data dictionary parser still naively assumes a one-to-one correspondence between every data dictionary entry, and every column of data in the actual data CSV. This was proven not to be the case in two examples:

  1.  Descriptive fields: these are purely informative. While they are defined in the data dictionary and show content on the REDCap UI, they do not actually have corresponding columns created in the data CSV.
  2.  Multichoice fields: a multichoice field like a checkbox actually results in the creation of multiple columns in the underlying data CSV, one for each checkbox option.

The first case (1.) can be handled relatively painlessly, but the second case where a data dictionary field may yield multiple, possibly dozens of data csv columns was not accounted for in the design of the main parsing loop.

Hence, the current code is unable to handle multichoice fields like checkboxes at all, and attempting to integrate support into it would not be feasible. This is because the main parsing loop creates a key-value pair in the schema for every data dictionary entry, and we cannot create multiple key-value pairs due to the way the loop is architectured:

class Parser(ParseByFieldType):

    # ...

    def create_schema(self) -> dict:

        # ...

        # Iterate over indexes and rows in the data dictionary, storing them in columns

        for index, row in self.data_dict.iterrows():

            columns[index] = self.__parse_field_type(row)

    # ...

We will probably have to rewrite the parser and the main loop as a result.

**Comment by ShenZhouHong** [comment]
I agree that the creation of the actual choice columns for the checkbox fields is not a difficulty. In fact, we actually implemented support for parsing the `row["select_choices_or_calculations"]` string in the [latest commit](https://github.com/metrc/redcapschema/commit/28f09c5b103e3647ebd019f275218d4556c987a3).

The main difficulty is that the `create_schema()` method essentially appends a single new key-value pair to the schema dictionary for every field in the data dictionary:

```py
for index, row in self.data_dict.iterrows():
    columns[index] = self.__parse_field_type(row)
```

This is hardcoded both in the loop itself, as well as in the assumptions of the return values for all the methods, which all ultimately return a Pandera `Column` with the appropriate constraints.

In order to support this, we must probably refactor `create_schema()` so that each underlying `ParseByFieldType()` method is responsible for appending key-value pair(s) to the schema, and not the loop itself.

Thankfully, this is not an unduly difficult task, it will only require the factoring of at most two or three classes.

**Comment by ShenZhouHong** [comment]
This issue is solved with this commit:
https://github.com/metrc/redcapschema/commit/b4d4da6714bfc2bca1d9dd409b8da0e2dfb10eaa

For more information, see the commit message:

> This commit solves the issue by refactoring the Parser and the
ParseByFieldType classes to not return individual columns for appending
into the columns dictionary, but to return dictionaries themselves. The
main loop now proceeds to merge each returned dictionary into the
self.schema dict.
>
> This allows individual parsers (e.g. parse_checkbox) to return a schema
fragment dict containing multiple Column entries that are then merged
into self.schema. It also allows parsers like parse_descriptive()
to return no entries in the form of an empty dict {Solves issue https://github.com/metrc/redcapschema/issues/1.
Originally, the parser assumed a 1-to-1 relationship
between REDCap Data Dictionary entries, and columns in the REDcap data
csv. This assumption is incorrect, as documented in:
https://github.com/metrc/redcapschema/issues/1
>
> This commit solves the issue by refactoring the Parser and the
ParseByFieldType classes to not return individual columns for appending
into the columns dictionary, but to return dictionaries themselves. The
main loop now proceeds to merge each returned dictionary into the
self.schema dict.
>
> This allows individual parsers (e.g. parse_checkbox) to return a schema
fragment dict containing multiple Column entries that are then merged
into self.schema. It also allows parsers like parse_descriptive()
to return no entries in the form of an empty dict {}.
